#!/usr/bin/env bash

# Setup
set -x
set -e

export LC_ALL=C

source /common.sh
install_cleanup_trap

# Install pre-release pi-top repo source
apt-get install -y pi-top-os-unstable-apt-source
apt-get update
# Install headless services
apt-get install -y --no-install-recommends \
  pi-topd \
  pt-miniscreen \
  xprintidle # Needed until released: https://github.com/pi-top/pi-topd/pull/143

# Install additional device support (e.g. touchscreen, display port, firmware update)
# https://github.com/pi-top/pi-topOS-Core-Packages/blob/927828f4e577cc4718d541c4afc3e1e74bb113b4/debian/control#L49-L60
# apt-get install -y --no-install-recommends pt-device-support
