#!/usr/bin/env bash

# Setup
set -x
set -e

export LC_ALL=C

source /common.sh
install_cleanup_trap

# Install pre-release pi-top repo source
apt-get install -y pi-top-os-unstable-apt-source
apt-get update
# Install pi-topd service
apt-get install -y --no-install-recommends pi-topd
